// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _17042020_Create_Table_Demo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17042020_Create_Table_Demo));
        
        string IMigrationMetadata.Id
        {
            get { return "202004171245029_17042020_Create_Table_Demo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
