SET IDENTITY_INSERT dbo.Provinces ON
INSERT INTO dbo.Provinces(Id,Name,Type) VALUES 
(01, N'Thành phố Hà Nội', N'Thành phố Trung ương'),
(02, N'Tỉnh Hà Giang', N'Tỉnh'),
(04, N'Tỉnh Cao Bằng', N'Tỉnh'),
(06, N'Tỉnh Bắc Kạn', N'Tỉnh'),
(08, N'Tỉnh Tuyên Quang', N'Tỉnh'),
(10, N'Tỉnh Lào Cai', N'Tỉnh'),
(11, N'Tỉnh Điện Biên', N'Tỉnh'),
(12, N'Tỉnh Lai Châu', N'Tỉnh'),
(14, N'Tỉnh Sơn La', N'Tỉnh'),
(15, N'Tỉnh Yên Bái', N'Tỉnh'),
(17, N'Tỉnh Hoà Bình', N'Tỉnh'),
(19, N'Tỉnh Thái Nguyên', N'Tỉnh'),
(20, N'Tỉnh Lạng Sơn', N'Tỉnh'),
(22, N'Tỉnh Quảng Ninh', N'Tỉnh'),
(24, N'Tỉnh Bắc Giang', N'Tỉnh'),
(25, N'Tỉnh Phú Thọ', N'Tỉnh'),
(26, N'Tỉnh Vĩnh Phúc', N'Tỉnh'),
(27, N'Tỉnh Bắc Ninh', N'Tỉnh'),
(30, N'Tỉnh Hải Dương', N'Tỉnh'),
(31, N'Thành phố Hải Phòng', N'Thành phố Trung ương'),
(33, N'Tỉnh Hưng Yên', N'Tỉnh'),
(34, N'Tỉnh Thái Bình', N'Tỉnh'),
(35, N'Tỉnh Hà Nam', N'Tỉnh'),
(36, N'Tỉnh Nam Định', N'Tỉnh'),
(37, N'Tỉnh Ninh Bình', N'Tỉnh'),
(38, N'Tỉnh Thanh Hóa', N'Tỉnh'),
(40, N'Tỉnh Nghệ An', N'Tỉnh'),
(42, N'Tỉnh Hà Tĩnh', N'Tỉnh'),
(44, N'Tỉnh Quảng Bình', N'Tỉnh'),
(45, N'Tỉnh Quảng Trị', N'Tỉnh'),
(46, N'Tỉnh Thừa Thiên Huế', N'Tỉnh'),
(48, N'Thành phố Đà Nẵng', N'Thành phố Trung ương'),
(49, N'Tỉnh Quảng Nam', N'Tỉnh'),
(51, N'Tỉnh Quảng Ngãi', N'Tỉnh'),
(52, N'Tỉnh Bình Định', N'Tỉnh'),
(54, N'Tỉnh Phú Yên', N'Tỉnh'),
(56, N'Tỉnh Khánh Hòa', N'Tỉnh'),
(58, N'Tỉnh Ninh Thuận', N'Tỉnh'),
(60, N'Tỉnh Bình Thuận', N'Tỉnh'),
(62, N'Tỉnh Kon Tum', N'Tỉnh'),
(64, N'Tỉnh Gia Lai', N'Tỉnh'),
(66, N'Tỉnh Đắk Lắk', N'Tỉnh'),
(67, N'Tỉnh Đắk Nông', N'Tỉnh'),
(68, N'Tỉnh Lâm Đồng', N'Tỉnh'),
(70, N'Tỉnh Bình Phước', N'Tỉnh'),
(72, N'Tỉnh Tây Ninh', N'Tỉnh'),
(74, N'Tỉnh Bình Dương', N'Tỉnh'),
(75, N'Tỉnh Đồng Nai', N'Tỉnh'),
(77, N'Tỉnh Bà Rịa - Vũng Tàu', N'Tỉnh'),
(79, N'Thành phố Hồ Chí Minh', N'Thành phố Trung ương'),
(80, N'Tỉnh Long An', N'Tỉnh'),
(82, N'Tỉnh Tiền Giang', N'Tỉnh'),
(83, N'Tỉnh Bến Tre', N'Tỉnh'),
(84, N'Tỉnh Trà Vinh', N'Tỉnh'),
(86, N'Tỉnh Vĩnh Long', N'Tỉnh'),
(87, N'Tỉnh Đồng Tháp', N'Tỉnh'),
(89, N'Tỉnh An Giang', N'Tỉnh'),
(91, N'Tỉnh Kiên Giang', N'Tỉnh'),
(92, N'Thành phố Cần Thơ', N'Thành phố Trung ương'),
(93, N'Tỉnh Hậu Giang', N'Tỉnh'),
(94, N'Tỉnh Sóc Trăng', N'Tỉnh'),
(95, N'Tỉnh Bạc Liêu', N'Tỉnh'),
(96, N'Tỉnh Cà Mau', N'Tỉnh');

SET IDENTITY_INSERT dbo.Provinces OFF